[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run nx run-many -t build"]

[start]
cmd = "node backend/dist/main.js"

[variables]
NODE_ENV = "production"
