import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: './openapi.json',
    output: {
      target: './src/api/generated/hooks.ts',
      schemas: './src/api/generated/schemas',
      client: 'react-query',
      mode: 'tags-split',
      mock: false,
      override: {
        query: {
          useQuery: true,
          useSuspenseQuery: true,
          useInfiniteQuery: true,
          useMutation: true,
        },
        mutator: {
          path: './src/api/orval-client.ts',
          name: 'customInstance',
        },
        header: '// Auto-generated by orval — DO NOT EDIT\n// npm run generate:api',
      },
    },
  },
});
